import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1755206076415 implements MigrationInterface {
    name = 'InitMigration1755206076415'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_notification" DROP CONSTRAINT "fk_user_notification_type"`);
        await queryRunner.query(`ALTER TABLE "user_notification" DROP CONSTRAINT "fk_user"`);
        await queryRunner.query(`ALTER TABLE "import_templates" DROP CONSTRAINT "FK_import_templates_creator"`);
        await queryRunner.query(`ALTER TABLE "import_templates" DROP CONSTRAINT "FK_import_templates_organization"`);
        await queryRunner.query(`ALTER TABLE "import_history" DROP CONSTRAINT "FK_import_history_creator"`);
        await queryRunner.query(`ALTER TABLE "import_history" DROP CONSTRAINT "FK_import_history_organization"`);
        await queryRunner.query(`ALTER TABLE "batch" DROP CONSTRAINT "FK_batch_organization"`);
        await queryRunner.query(`ALTER TABLE "batch" DROP CONSTRAINT "FK_batch_package"`);
        await queryRunner.query(`ALTER TABLE "booking_passengers" DROP CONSTRAINT "FK_booking_passengers_booking"`);
        await queryRunner.query(`ALTER TABLE "booking_documents" DROP CONSTRAINT "FK_booking_documents_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "booking_documents" DROP CONSTRAINT "FK_booking_documents_booking"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_organization"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_created_by"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_batch"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_package"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_customer"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" DROP CONSTRAINT "FK_booking_payments_recorded_by"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" DROP CONSTRAINT "FK_booking_payments_booking"`);
        await queryRunner.query(`ALTER TABLE "batch_coordinators" DROP CONSTRAINT "FK_batch_employee"`);
        await queryRunner.query(`ALTER TABLE "batch_passengers" DROP CONSTRAINT "FK_batch_customer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_passengers_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_documents_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_organization_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_customer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_booking_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_payments_booking_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "organization_id" uuid`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "created_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "notifications_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "newsletter_subscribed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_notification" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_notification" ALTER COLUMN "user_notification_type_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" DROP COLUMN "text"`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" ADD "text" text`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" DROP COLUMN "percentage"`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" ADD "percentage" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "checklist_items" DROP COLUMN "category"`);
        await queryRunner.query(`CREATE TYPE "public"."checklist_items_category_enum" AS ENUM('documents', 'booking', 'preparation', 'communication')`);
        await queryRunner.query(`ALTER TABLE "checklist_items" ADD "category" "public"."checklist_items_category_enum"`);
        await queryRunner.query(`ALTER TABLE "checklist_items" ALTER COLUMN "completed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_requirements" ALTER COLUMN "mandatory" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "document_requirements" ALTER COLUMN "mandatory" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "document_requirements" DROP COLUMN "applicableFor"`);
        await queryRunner.query(`CREATE TYPE "public"."document_requirements_applicablefor_enum" AS ENUM('adults', 'children', 'all')`);
        await queryRunner.query(`ALTER TABLE "document_requirements" ADD "applicableFor" "public"."document_requirements_applicablefor_enum"`);
        await queryRunner.query(`ALTER TABLE "exclusions" DROP COLUMN "item"`);
        await queryRunner.query(`ALTER TABLE "exclusions" ADD "item" text`);
        await queryRunner.query(`ALTER TABLE "inclusions" DROP COLUMN "item"`);
        await queryRunner.query(`ALTER TABLE "inclusions" ADD "item" text`);
        await queryRunner.query(`ALTER TABLE "meals_breakdowns" ADD CONSTRAINT "UQ_038ffcd4d91bb711c4e36ff303b" UNIQUE ("packageId")`);
        await queryRunner.query(`ALTER TABLE "package_locations" ADD CONSTRAINT "UQ_44e82dd5332ff06ff5bae4aca7c" UNIQUE ("packageId")`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" DROP COLUMN "percentage"`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" ADD "percentage" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "toIncluded" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "toIncluded" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "fromIncluded" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "fromIncluded" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "duringIncluded" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "duringIncluded" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "transportations" ADD CONSTRAINT "UQ_2e0d65158ae1d3a017790dc3a29" UNIQUE ("packageId")`);
        await queryRunner.query(`ALTER TABLE "packages" DROP COLUMN "difficulty"`);
        await queryRunner.query(`CREATE TYPE "public"."packages_difficulty_enum" AS ENUM('easy', 'moderate', 'challenging', 'extreme')`);
        await queryRunner.query(`ALTER TABLE "packages" ADD "difficulty" "public"."packages_difficulty_enum"`);
        await queryRunner.query(`ALTER TABLE "packages" DROP COLUMN "category"`);
        await queryRunner.query(`CREATE TYPE "public"."packages_category_enum" AS ENUM('adventure', 'cultural', 'relaxation', 'wildlife', 'luxury', 'budget')`);
        await queryRunner.query(`ALTER TABLE "packages" ADD "category" "public"."packages_category_enum"`);
        await queryRunner.query(`ALTER TABLE "packages" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."packages_status_enum" AS ENUM('draft', 'published')`);
        await queryRunner.query(`ALTER TABLE "packages" ADD "status" "public"."packages_status_enum" DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "batch" ALTER COLUMN "booked_seats" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "batch" ALTER COLUMN "booked_seats" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TYPE "public"."document_type_enum" RENAME TO "document_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."booking_documents_documenttype_enum" AS ENUM('booking_confirmation', 'payment_receipt', 'travel_itinerary', 'passport_copy', 'visa_copy', 'insurance_document', 'other')`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" TYPE "public"."booking_documents_documenttype_enum" USING "documentType"::"text"::"public"."booking_documents_documenttype_enum"`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" SET DEFAULT 'other'`);
        await queryRunner.query(`DROP TYPE "public"."document_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "advance_paid" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."booking_status_enum" RENAME TO "booking_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'confirmed', 'cancelled', 'completed')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" TYPE "public"."bookings_status_enum" USING "status"::"text"::"public"."bookings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."payment_type_enum" RENAME TO "payment_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."booking_payments_payment_type_enum" AS ENUM('advance', 'balance', 'partial', 'refund')`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "payment_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "payment_type" TYPE "public"."booking_payments_payment_type_enum" USING "payment_type"::"text"::"public"."booking_payments_payment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "payment_type" SET DEFAULT 'advance'`);
        await queryRunner.query(`DROP TYPE "public"."payment_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum" RENAME TO "payment_method_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."booking_payments_paymentmethod_enum" AS ENUM('bank_transfer', 'credit_card', 'debit_card', 'cash', 'upi', 'other')`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "paymentMethod" TYPE "public"."booking_payments_paymentmethod_enum" USING "paymentMethod"::"text"::"public"."booking_payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum" RENAME TO "payment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."booking_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'refunded', 'archived')`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" TYPE "public"."booking_payments_status_enum" USING "status"::"text"::"public"."booking_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE INDEX "IDX_08626ad212783d6b0fc7d3f513" ON "batch_coordinators" ("batchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d68a1efe3667f2bfeb01b93730" ON "batch_coordinators" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e87d0380e13e11f53e121e8739" ON "batch_passengers" ("batchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0442b18cb1254c9f2bb48036c" ON "batch_passengers" ("customerId") `);
        await queryRunner.query(`ALTER TABLE "user_notification" ADD CONSTRAINT "FK_ed67d2f825f4103de44ec3b6ba7" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification" ADD CONSTRAINT "FK_e95e0954a0504c9f873621a5c38" FOREIGN KEY ("user_notification_type_id") REFERENCES "user_notification_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_templates" ADD CONSTRAINT "FK_8bd73a1739211d4245637139a1e" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_templates" ADD CONSTRAINT "FK_164e488c510a93859d591388f9d" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_history" ADD CONSTRAINT "FK_71cdae429e95acc9911205fd6ec" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_history" ADD CONSTRAINT "FK_aba8a73b613296c11d8f41e0ebc" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_4ffb356b370e38bdf5502ce44df" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_f59a476121c4fe9ea136699a95d" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" ADD CONSTRAINT "FK_3d7697fa4872ca571f1c63d7f23" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" ADD CONSTRAINT "FK_5ac9df41946608c0e524ac3cdba" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist_items" ADD CONSTRAINT "FK_5e5d30b7e402798ef0dcbff6c7d" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_requirements" ADD CONSTRAINT "FK_ad0ce6df1dc7f9aab500b9da68c" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exclusions" ADD CONSTRAINT "FK_000d7f18a5e0ea5e98cafa65586" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inclusions" ADD CONSTRAINT "FK_41bd41ae10f66514c4c4fcc4cd3" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itinerary_days" ADD CONSTRAINT "FK_77692f06767f14e5dd5fe15a6b0" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meals_breakdowns" ADD CONSTRAINT "FK_038ffcd4d91bb711c4e36ff303b" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "package_locations" ADD CONSTRAINT "FK_44e82dd5332ff06ff5bae4aca7c" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" ADD CONSTRAINT "FK_afcc7fa914330d69f5ae8c4b04a" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transportations" ADD CONSTRAINT "FK_2e0d65158ae1d3a017790dc3a29" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "packages" ADD CONSTRAINT "FK_98b16f59b717e596ae85197a0af" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "packages" ADD CONSTRAINT "FK_5eca6d2623430d34c051700807f" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch" ADD CONSTRAINT "FK_f1506453e23e01035d827618b3e" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch" ADD CONSTRAINT "FK_3bfa6644f378ef3cc5bdb37f956" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_passengers" ADD CONSTRAINT "FK_1e2d37c7eb82f4017a9a4a06bc8" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ADD CONSTRAINT "FK_b4cd5c837329d17508808dc0938" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ADD CONSTRAINT "FK_e02a0906cc18af4e45507f1c656" FOREIGN KEY ("uploaded_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_402873fd6596d556781ac5d8ae4" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bfe433b9d4bd27eb45ee01274c0" FOREIGN KEY ("batch_id") REFERENCES "batch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_2ab7f927262f1f56d6f45bca107" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_1b3f0fcfa5c68dffbfd47cbb103" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ADD CONSTRAINT "FK_afaa5733b05d8844072d5107eae" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ADD CONSTRAINT "FK_4939aad83daac5e7c0756cb308b" FOREIGN KEY ("recorded_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_coordinators" ADD CONSTRAINT "FK_08626ad212783d6b0fc7d3f513f" FOREIGN KEY ("batchId") REFERENCES "batch"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "batch_coordinators" ADD CONSTRAINT "FK_d68a1efe3667f2bfeb01b937303" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "batch_passengers" ADD CONSTRAINT "FK_e87d0380e13e11f53e121e8739a" FOREIGN KEY ("batchId") REFERENCES "batch"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "batch_passengers" ADD CONSTRAINT "FK_f0442b18cb1254c9f2bb48036c9" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "batch_passengers" DROP CONSTRAINT "FK_f0442b18cb1254c9f2bb48036c9"`);
        await queryRunner.query(`ALTER TABLE "batch_passengers" DROP CONSTRAINT "FK_e87d0380e13e11f53e121e8739a"`);
        await queryRunner.query(`ALTER TABLE "batch_coordinators" DROP CONSTRAINT "FK_d68a1efe3667f2bfeb01b937303"`);
        await queryRunner.query(`ALTER TABLE "batch_coordinators" DROP CONSTRAINT "FK_08626ad212783d6b0fc7d3f513f"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" DROP CONSTRAINT "FK_4939aad83daac5e7c0756cb308b"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" DROP CONSTRAINT "FK_afaa5733b05d8844072d5107eae"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_1b3f0fcfa5c68dffbfd47cbb103"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_2ab7f927262f1f56d6f45bca107"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bfe433b9d4bd27eb45ee01274c0"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_402873fd6596d556781ac5d8ae4"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f"`);
        await queryRunner.query(`ALTER TABLE "booking_documents" DROP CONSTRAINT "FK_e02a0906cc18af4e45507f1c656"`);
        await queryRunner.query(`ALTER TABLE "booking_documents" DROP CONSTRAINT "FK_b4cd5c837329d17508808dc0938"`);
        await queryRunner.query(`ALTER TABLE "booking_passengers" DROP CONSTRAINT "FK_1e2d37c7eb82f4017a9a4a06bc8"`);
        await queryRunner.query(`ALTER TABLE "batch" DROP CONSTRAINT "FK_3bfa6644f378ef3cc5bdb37f956"`);
        await queryRunner.query(`ALTER TABLE "batch" DROP CONSTRAINT "FK_f1506453e23e01035d827618b3e"`);
        await queryRunner.query(`ALTER TABLE "packages" DROP CONSTRAINT "FK_5eca6d2623430d34c051700807f"`);
        await queryRunner.query(`ALTER TABLE "packages" DROP CONSTRAINT "FK_98b16f59b717e596ae85197a0af"`);
        await queryRunner.query(`ALTER TABLE "transportations" DROP CONSTRAINT "FK_2e0d65158ae1d3a017790dc3a29"`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" DROP CONSTRAINT "FK_afcc7fa914330d69f5ae8c4b04a"`);
        await queryRunner.query(`ALTER TABLE "package_locations" DROP CONSTRAINT "FK_44e82dd5332ff06ff5bae4aca7c"`);
        await queryRunner.query(`ALTER TABLE "meals_breakdowns" DROP CONSTRAINT "FK_038ffcd4d91bb711c4e36ff303b"`);
        await queryRunner.query(`ALTER TABLE "itinerary_days" DROP CONSTRAINT "FK_77692f06767f14e5dd5fe15a6b0"`);
        await queryRunner.query(`ALTER TABLE "inclusions" DROP CONSTRAINT "FK_41bd41ae10f66514c4c4fcc4cd3"`);
        await queryRunner.query(`ALTER TABLE "exclusions" DROP CONSTRAINT "FK_000d7f18a5e0ea5e98cafa65586"`);
        await queryRunner.query(`ALTER TABLE "document_requirements" DROP CONSTRAINT "FK_ad0ce6df1dc7f9aab500b9da68c"`);
        await queryRunner.query(`ALTER TABLE "checklist_items" DROP CONSTRAINT "FK_5e5d30b7e402798ef0dcbff6c7d"`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" DROP CONSTRAINT "FK_5ac9df41946608c0e524ac3cdba"`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" DROP CONSTRAINT "FK_3d7697fa4872ca571f1c63d7f23"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_f59a476121c4fe9ea136699a95d"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_4ffb356b370e38bdf5502ce44df"`);
        await queryRunner.query(`ALTER TABLE "import_history" DROP CONSTRAINT "FK_aba8a73b613296c11d8f41e0ebc"`);
        await queryRunner.query(`ALTER TABLE "import_history" DROP CONSTRAINT "FK_71cdae429e95acc9911205fd6ec"`);
        await queryRunner.query(`ALTER TABLE "import_templates" DROP CONSTRAINT "FK_164e488c510a93859d591388f9d"`);
        await queryRunner.query(`ALTER TABLE "import_templates" DROP CONSTRAINT "FK_8bd73a1739211d4245637139a1e"`);
        await queryRunner.query(`ALTER TABLE "user_notification" DROP CONSTRAINT "FK_e95e0954a0504c9f873621a5c38"`);
        await queryRunner.query(`ALTER TABLE "user_notification" DROP CONSTRAINT "FK_ed67d2f825f4103de44ec3b6ba7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0442b18cb1254c9f2bb48036c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e87d0380e13e11f53e121e8739"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d68a1efe3667f2bfeb01b93730"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08626ad212783d6b0fc7d3f513"`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum_old" AS ENUM('pending', 'completed', 'failed', 'refunded', 'archived')`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" TYPE "public"."payment_status_enum_old" USING "status"::"text"::"public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."booking_payments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum_old" RENAME TO "payment_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_enum_old" AS ENUM('bank_transfer', 'credit_card', 'debit_card', 'cash', 'upi', 'other')`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "paymentMethod" TYPE "public"."payment_method_enum_old" USING "paymentMethod"::"text"::"public"."payment_method_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."booking_payments_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum_old" RENAME TO "payment_method_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_type_enum_old" AS ENUM('advance', 'balance', 'partial', 'refund')`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "payment_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "payment_type" TYPE "public"."payment_type_enum_old" USING "payment_type"::"text"::"public"."payment_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ALTER COLUMN "payment_type" SET DEFAULT 'advance'`);
        await queryRunner.query(`DROP TYPE "public"."booking_payments_payment_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_type_enum_old" RENAME TO "payment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_enum_old" AS ENUM('pending', 'confirmed', 'cancelled', 'completed')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" TYPE "public"."booking_status_enum_old" USING "status"::"text"::"public"."booking_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."booking_status_enum_old" RENAME TO "booking_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "advance_paid" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."document_type_enum_old" AS ENUM('booking_confirmation', 'payment_receipt', 'travel_itinerary', 'passport_copy', 'visa_copy', 'insurance_document', 'other')`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" TYPE "public"."document_type_enum_old" USING "documentType"::"text"::"public"."document_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ALTER COLUMN "documentType" SET DEFAULT 'other'`);
        await queryRunner.query(`DROP TYPE "public"."booking_documents_documenttype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."document_type_enum_old" RENAME TO "document_type_enum"`);
        await queryRunner.query(`ALTER TABLE "batch" ALTER COLUMN "booked_seats" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "batch" ALTER COLUMN "booked_seats" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "packages" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."packages_status_enum"`);
        await queryRunner.query(`ALTER TABLE "packages" ADD "status" character varying DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "packages" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."packages_category_enum"`);
        await queryRunner.query(`ALTER TABLE "packages" ADD "category" character varying`);
        await queryRunner.query(`ALTER TABLE "packages" DROP COLUMN "difficulty"`);
        await queryRunner.query(`DROP TYPE "public"."packages_difficulty_enum"`);
        await queryRunner.query(`ALTER TABLE "packages" ADD "difficulty" character varying`);
        await queryRunner.query(`ALTER TABLE "transportations" DROP CONSTRAINT "UQ_2e0d65158ae1d3a017790dc3a29"`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "duringIncluded" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "duringIncluded" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "fromIncluded" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "fromIncluded" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "toIncluded" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transportations" ALTER COLUMN "toIncluded" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" DROP COLUMN "percentage"`);
        await queryRunner.query(`ALTER TABLE "payment_milestones" ADD "percentage" integer`);
        await queryRunner.query(`ALTER TABLE "package_locations" DROP CONSTRAINT "UQ_44e82dd5332ff06ff5bae4aca7c"`);
        await queryRunner.query(`ALTER TABLE "meals_breakdowns" DROP CONSTRAINT "UQ_038ffcd4d91bb711c4e36ff303b"`);
        await queryRunner.query(`ALTER TABLE "inclusions" DROP COLUMN "item"`);
        await queryRunner.query(`ALTER TABLE "inclusions" ADD "item" character varying`);
        await queryRunner.query(`ALTER TABLE "exclusions" DROP COLUMN "item"`);
        await queryRunner.query(`ALTER TABLE "exclusions" ADD "item" character varying`);
        await queryRunner.query(`ALTER TABLE "document_requirements" DROP COLUMN "applicableFor"`);
        await queryRunner.query(`DROP TYPE "public"."document_requirements_applicablefor_enum"`);
        await queryRunner.query(`ALTER TABLE "document_requirements" ADD "applicableFor" character varying`);
        await queryRunner.query(`ALTER TABLE "document_requirements" ALTER COLUMN "mandatory" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "document_requirements" ALTER COLUMN "mandatory" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklist_items" ALTER COLUMN "completed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklist_items" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."checklist_items_category_enum"`);
        await queryRunner.query(`ALTER TABLE "checklist_items" ADD "category" character varying`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" DROP COLUMN "percentage"`);
        await queryRunner.query(`ALTER TABLE "cancellation_tiers" ADD "percentage" integer`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" DROP COLUMN "text"`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" ADD "text" character varying`);
        await queryRunner.query(`ALTER TABLE "user_notification" ALTER COLUMN "user_notification_type_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_notification" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "newsletter_subscribed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "notifications_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`CREATE INDEX "IDX_booking_payments_booking_id" ON "booking_payments" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_booking_number" ON "bookings" ("booking_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_created_at" ON "bookings" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_status" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_customer_id" ON "bookings" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_organization_id" ON "bookings" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_documents_booking_id" ON "booking_documents" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_passengers_booking_id" ON "booking_passengers" ("booking_id") `);
        await queryRunner.query(`ALTER TABLE "batch_passengers" ADD CONSTRAINT "FK_batch_customer" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch_coordinators" ADD CONSTRAINT "FK_batch_employee" FOREIGN KEY ("employeeId") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ADD CONSTRAINT "FK_booking_payments_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_payments" ADD CONSTRAINT "FK_booking_payments_recorded_by" FOREIGN KEY ("recorded_by_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_customer" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_package" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_batch" FOREIGN KEY ("batch_id") REFERENCES "batch"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_created_by" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ADD CONSTRAINT "FK_booking_documents_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_documents" ADD CONSTRAINT "FK_booking_documents_uploaded_by" FOREIGN KEY ("uploaded_by_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_passengers" ADD CONSTRAINT "FK_booking_passengers_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch" ADD CONSTRAINT "FK_batch_package" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batch" ADD CONSTRAINT "FK_batch_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_history" ADD CONSTRAINT "FK_import_history_organization" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_history" ADD CONSTRAINT "FK_import_history_creator" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_templates" ADD CONSTRAINT "FK_import_templates_organization" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_templates" ADD CONSTRAINT "FK_import_templates_creator" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification" ADD CONSTRAINT "fk_user_notification_type" FOREIGN KEY ("user_notification_type_id") REFERENCES "user_notification_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
