import { ILead } from '@repo/api/lead/lead.entity';

export const mockLeads: ILead[] = [
  {
    id: '1',
    name: 'John Smith',
    company: 'Acme Inc',
    email: 'john.smith@acme.com',
    phone: '(555) 123-4567',
    status: 'new',
    createdAt: '2023-05-15T10:30:00Z',
    notes: 'Met at the tech conference',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    company: 'TechCorp',
    email: 'sarah.j@techcorp.com',
    phone: '(555) 234-5678',
    status: 'contacted',
    createdAt: '2023-05-10T14:45:00Z',
    notes: 'Interested in enterprise plan',
  },
  {
    id: '3',
    name: 'Michael Brown',
    company: 'Global Solutions',
    email: 'm.brown@globalsolutions.com',
    phone: '(555) 345-6789',
    status: 'qualified',
    createdAt: '2023-05-05T09:15:00Z',
    notes: 'Needs custom integration',
  },
  {
    id: '4',
    name: 'Emily Davis',
    company: 'Innovate LLC',
    email: 'emily@innovatellc.com',
    phone: '(555) 456-7890',
    status: 'lost',
    createdAt: '2023-04-28T11:00:00Z',
    notes: 'Budget constraints',
  },
  {
    id: '5',
    name: 'David Wilson',
    company: 'NextGen Systems',
    email: 'david.w@nextgensystems.com',
    phone: '(555) 567-8901',
    status: 'converted',
    createdAt: '2023-04-20T16:30:00Z',
    notes: 'Signed annual contract',
  },
  {
    id: '6',
    name: 'Jennifer Lee',
    company: 'Bright Ideas Co',
    email: 'jennifer@brightideas.co',
    phone: '(555) 678-9012',
    status: 'new',
    createdAt: '2023-05-18T13:20:00Z',
    notes: 'Referral from David Wilson',
  },
  {
    id: '7',
    name: 'Robert Taylor',
    company: 'Modern Solutions',
    email: 'robert@modernsolutions.com',
    phone: '(555) 789-0123',
    status: 'contacted',
    createdAt: '2023-05-12T10:00:00Z',
    notes: 'Follow up next week',
  },
  {
    id: '8',
    name: 'Lisa Anderson',
    company: 'Peak Performance',
    email: 'lisa@peakperformance.org',
    phone: '(555) 890-1234',
    status: 'qualified',
    createdAt: '2023-05-08T15:45:00Z',
    notes: 'Interested in premium features',
  },
  {
    id: '9',
    name: 'James Martin',
    company: 'Elite Enterprises',
    email: 'james@eliteenterprises.com',
    phone: '(555) 901-2345',
    status: 'lost',
    createdAt: '2023-04-25T09:30:00Z',
    notes: 'Went with competitor',
  },
];
