/**
 * Default permission sets configuration
 * These will be created for each organization
 */

export interface DefaultPermissionSetConfig {
  name: string;
  description: string;
  permissionNames: string[];
}

export type DefaultPermissionSetRole =
  | 'admin'
  | 'manager'
  | 'finance_manager'
  | 'finance_employee'
  | 'booking_manager'
  | 'booking_employee'
  | 'leads_manager'
  | 'leads_employee'
  | 'operations_manager'
  | 'operations_employee'
  | 'employee';

export const defaultPermissionSets: Record<
  DefaultPermissionSetRole,
  DefaultPermissionSetConfig
> = {
  admin: {
    name: 'Admin - Full Access',
    description: 'Full access to all system features and settings',
    permissionNames: [
      'booking.create',
      'booking.read',
      'booking.update',
      'booking.delete',
      'booking.view',
      'lead.create',
      'lead.read',
      'lead.update',
      'lead.delete',
      'lead.view',
      'package.create',
      'package.read',
      'package.update',
      'package.delete',
      'package.view',
      'customer.create',
      'customer.read',
      'customer.update',
      'customer.delete',
      'customer.view',
      'employee.create',
      'employee.read',
      'employee.update',
      'employee.delete',
      'employee.view',
      'employee.manage',
      'payment.create',
      'payment.read',
      'payment.update',
      'payment.delete',
      'payment.view',
      'batch.create',
      'batch.read',
      'batch.update',
      'batch.delete',
      'batch.view',
      'branch.create',
      'branch.read',
      'branch.update',
      'branch.delete',
      'branch.view',
      'department.create',
      'department.read',
      'department.update',
      'department.delete',
      'department.view',
      'role.create',
      'role.read',
      'role.update',
      'role.delete',
      'role.view',
      'role.manage',
      'permission.create',
      'permission.read',
      'permission.update',
      'permission.delete',
      'permission.view',
      'permission.manage',
      'permission-set.create',
      'permission-set.read',
      'permission-set.update',
      'permission-set.delete',
      'permission-set.view',
      'permission-set.manage',
      'workflow.create',
      'workflow.read',
      'workflow.update',
      'workflow.delete',
      'workflow.view',
    ],
  },
  manager: {
    name: 'General Manager',
    description: 'Broad access to manage all departments and operations',
    permissionNames: [
      'booking.create',
      'booking.read',
      'booking.update',
      'booking.view',
      'lead.create',
      'lead.read',
      'lead.update',
      'lead.view',
      'package.create',
      'package.read',
      'package.update',
      'package.view',
      'customer.create',
      'customer.read',
      'customer.update',
      'customer.view',
      'employee.read',
      'employee.view',
      'payment.create',
      'payment.read',
      'payment.update',
      'payment.view',
      'batch.create',
      'batch.read',
      'batch.update',
      'batch.view',
      'branch.read',
      'branch.view',
      'department.read',
      'department.view',
      'workflow.read',
      'workflow.update',
      'workflow.view',
    ],
  },
  finance_manager: {
    name: 'Finance Manager',
    description: 'Full access to financial records and payments',
    permissionNames: [
      'payment.create',
      'payment.read',
      'payment.update',
      'payment.delete',
      'payment.view',
      'customer.read',
      'customer.view',
      'booking.read',
      'booking.view',
    ],
  },
  finance_employee: {
    name: 'Finance Employee',
    description: 'Access to create and view payments',
    permissionNames: [
      'payment.create',
      'payment.read',
      'payment.view',
      'customer.read',
      'customer.view',
      'booking.read',
      'booking.view',
    ],
  },
  booking_manager: {
    name: 'Booking Manager',
    description: 'Manage all bookings, customers and packages',
    permissionNames: [
      'booking.create',
      'booking.read',
      'booking.update',
      'booking.delete',
      'booking.view',
      'customer.create',
      'customer.read',
      'customer.update',
      'customer.delete',
      'customer.view',
      'package.read',
      'package.view',
      'batch.read',
      'batch.view',
      'workflow.read',
      'workflow.update',
      'workflow.view',
    ],
  },
  booking_employee: {
    name: 'Booking Employee',
    description: 'Facilitate bookings and customer management',
    permissionNames: [
      'booking.create',
      'booking.read',
      'booking.update',
      'booking.view',
      'customer.create',
      'customer.read',
      'customer.update',
      'customer.view',
      'package.read',
      'package.view',
      'batch.read',
      'batch.view',
      'workflow.read',
      'workflow.update',
      'workflow.view',
    ],
  },
  leads_manager: {
    name: 'Leads Manager',
    description: 'Manage sales leads and customer acquisition',
    permissionNames: [
      'lead.create',
      'lead.read',
      'lead.update',
      'lead.delete',
      'lead.view',
      'customer.create',
      'customer.read',
      'customer.update',
      'customer.view',
    ],
  },
  leads_employee: {
    name: 'Leads Employee',
    description: 'Process and update sales leads',
    permissionNames: [
      'lead.create',
      'lead.read',
      'lead.update',
      'lead.view',
      'customer.create',
      'customer.read',
      'customer.view',
    ],
  },
  operations_manager: {
    name: 'Operations Manager',
    description: 'Manage batches, packages, and logistics',
    permissionNames: [
      'package.create',
      'package.read',
      'package.update',
      'package.delete',
      'package.view',
      'batch.create',
      'batch.read',
      'batch.update',
      'batch.delete',
      'batch.view',
      'branch.create',
      'branch.read',
      'branch.update',
      'branch.view',
      'department.read',
      'department.view',
      'booking.read',
      'booking.view',
      'workflow.read',
      'workflow.update',
      'workflow.view',
    ],
  },
  operations_employee: {
    name: 'Operations Employee',
    description: 'Support logistics and package management',
    permissionNames: [
      'package.create',
      'package.read',
      'package.update',
      'package.view',
      'batch.create',
      'batch.read',
      'batch.update',
      'batch.view',
      'branch.read',
      'branch.view',
      'department.read',
      'department.view',
      'workflow.read',
      'workflow.update',
      'workflow.view',
    ],
  },
  employee: {
    name: 'Employee - Basic Access',
    description:
      'Comprehensive access to view, create, and edit records (No Delete)',
    permissionNames: [
      'booking.create',
      'booking.read',
      'booking.update',
      'booking.view',
      'lead.create',
      'lead.read',
      'lead.update',
      'lead.view',
      'package.create',
      'package.read',
      'package.update',
      'package.view',
      'customer.create',
      'customer.read',
      'customer.update',
      'customer.view',
      'employee.read',
      'employee.view',
      'payment.create',
      'payment.read',
      'payment.update',
      'payment.view',
      'batch.create',
      'batch.read',
      'batch.update',
      'batch.view',
      'branch.read',
      'branch.view',
      'department.read',
      'department.view',
      'workflow.read',
      'workflow.update',
      'workflow.view',
    ],
  },
};
