export const batches = [
  // Himalayan Adventure Trek batches
  {
    startDate: '2025-03-15',
    endDate: '2025-03-28',
    totalSeats: 12,
    bookedSeats: 8,
    status: 'active',
    packageName: 'Himalayan Adventure Trek',
    organizationDomain: 'acme.com',
  },
  {
    startDate: '2025-04-10',
    endDate: '2025-04-23',
    totalSeats: 12,
    bookedSeats: 12,
    status: 'completed',
    packageName: 'Himalayan Adventure Trek',
    organizationDomain: 'acme.com',
  },
  {
    startDate: '2025-05-05',
    endDate: '2025-05-18',
    totalSeats: 12,
    bookedSeats: 5,
    status: 'active',
    packageName: 'Himalayan Adventure Trek',
    organizationDomain: 'acme.com',
  },

  // Cultural Heritage Tour of Rajasthan batches
  {
    startDate: '2025-02-20',
    endDate: '2025-03-01',
    totalSeats: 15,
    bookedSeats: 15,
    status: 'completed',
    packageName: 'Cultural Heritage Tour of Rajasthan',
    organizationDomain: 'globex.co',
  },
  {
    startDate: '2025-03-25',
    endDate: '2025-04-03',
    totalSeats: 15,
    bookedSeats: 10,
    status: 'active',
    packageName: 'Cultural Heritage Tour of Rajasthan',
    organizationDomain: 'globex.co',
  },
  {
    startDate: '2025-04-15',
    endDate: '2025-04-24',
    totalSeats: 15,
    bookedSeats: 3,
    status: 'active',
    packageName: 'Cultural Heritage Tour of Rajasthan',
    organizationDomain: 'globex.co',
  },

  // Tropical Paradise Getaway batches
  {
    startDate: '2025-02-10',
    endDate: '2025-02-16',
    totalSeats: 8,
    bookedSeats: 8,
    status: 'completed',
    packageName: 'Tropical Paradise Getaway',
    organizationDomain: 'initech.org',
  },
  {
    startDate: '2025-03-01',
    endDate: '2025-03-07',
    totalSeats: 8,
    bookedSeats: 6,
    status: 'active',
    packageName: 'Tropical Paradise Getaway',
    organizationDomain: 'initech.org',
  },
  {
    startDate: '2025-04-20',
    endDate: '2025-04-26',
    totalSeats: 8,
    bookedSeats: 2,
    status: 'active',
    packageName: 'Tropical Paradise Getaway',
    organizationDomain: 'initech.org',
  },

  // African Safari Adventure batches
  {
    startDate: '2025-06-01',
    endDate: '2025-06-12',
    totalSeats: 10,
    bookedSeats: 10,
    status: 'completed',
    packageName: 'African Safari Adventure',
    organizationDomain: 'umbrella.com',
  },
  {
    startDate: '2025-07-15',
    endDate: '2025-07-26',
    totalSeats: 10,
    bookedSeats: 7,
    status: 'active',
    packageName: 'African Safari Adventure',
    organizationDomain: 'umbrella.com',
  },
  {
    startDate: '2025-08-10',
    endDate: '2025-08-21',
    totalSeats: 10,
    bookedSeats: 4,
    status: 'active',
    packageName: 'African Safari Adventure',
    organizationDomain: 'umbrella.com',
  },

  // European Grand Tour batches
  {
    startDate: '2025-05-01',
    endDate: '2025-05-21',
    totalSeats: 20,
    bookedSeats: 18,
    status: 'active',
    packageName: 'European Grand Tour',
    organizationDomain: 'acme.com',
  },
  {
    startDate: '2025-06-15',
    endDate: '2025-07-05',
    totalSeats: 20,
    bookedSeats: 12,
    status: 'active',
    packageName: 'European Grand Tour',
    organizationDomain: 'acme.com',
  },
  {
    startDate: '2025-09-01',
    endDate: '2025-09-21',
    totalSeats: 20,
    bookedSeats: 5,
    status: 'active',
    packageName: 'European Grand Tour',
    organizationDomain: 'acme.com',
  },

  // Budget Backpacking Southeast Asia batches
  {
    startDate: '2025-03-01',
    endDate: '2025-03-18',
    totalSeats: 16,
    bookedSeats: 16,
    status: 'completed',
    packageName: 'Budget Backpacking Southeast Asia',
    organizationDomain: 'globex.co',
  },
  {
    startDate: '2025-04-15',
    endDate: '2025-05-02',
    totalSeats: 16,
    bookedSeats: 11,
    status: 'active',
    packageName: 'Budget Backpacking Southeast Asia',
    organizationDomain: 'globex.co',
  },
  {
    startDate: '2025-06-01',
    endDate: '2025-06-18',
    totalSeats: 16,
    bookedSeats: 8,
    status: 'active',
    packageName: 'Budget Backpacking Southeast Asia',
    organizationDomain: 'globex.co',
  },
];
