import { CustomerStatus } from '../entity/customer.entity';

export const customers = [
  {
    name: 'Alice Johnson',
    email: 'alice.johnson@email.com',
    phone: '+1-555-0201',
    address: '123 Main Street, New York, NY 10001',
    organizationDomain: 'acme.com',
    status: CustomerStatus.ACTIVE,
    notes: 'Regular customer, prefers luxury accommodations',
  },
  {
    name: 'Bob Smith',
    email: 'bob.smith@email.com',
    phone: '+1-555-0202',
    address: '456 Oak Avenue, Los Angeles, CA 90210',
    organizationDomain: 'globex.co',
    status: CustomerStatus.ACTIVE,
    notes: 'Adventure enthusiast, interested in extreme sports',
  },
  {
    name: 'Carol Williams',
    email: 'carol.williams@email.com',
    phone: '+1-555-0203',
    address: '789 Pine Road, Chicago, IL 60601',
    organizationDomain: 'initech.org',
    status: CustomerStatus.PENDING,
    notes: 'First-time customer, needs guidance on package selection',
  },
  {
    name: 'David Brown',
    email: 'david.brown@email.com',
    phone: '+1-555-0204',
    address: '321 Elm Street, Houston, TX 77001',
    organizationDomain: 'umbrella.com',
    status: CustomerStatus.ACTIVE,
    notes: 'Family traveler with young children',
  },
  {
    name: 'Eva Davis',
    email: 'eva.davis@email.com',
    phone: '+1-555-0205',
    address: '654 Maple Drive, Phoenix, AZ 85001',
    organizationDomain: 'acme.com',
    status: CustomerStatus.INACTIVE,
    notes: 'Inactive customer, last booking was 6 months ago',
  },
  {
    name: 'Frank Miller',
    email: 'frank.miller@email.com',
    phone: '+1-555-0206',
    address: '987 Cedar Lane, Philadelphia, PA 19101',
    organizationDomain: 'globex.co',
    status: CustomerStatus.ACTIVE,
    notes: 'Business traveler, frequently books last-minute trips',
  },
  {
    name: 'Grace Wilson',
    email: 'grace.wilson@email.com',
    phone: '+1-555-0207',
    address: '147 Birch Street, San Antonio, TX 78201',
    organizationDomain: 'initech.org',
    status: CustomerStatus.PENDING,
    notes: 'Senior traveler, requires accessible accommodations',
  },
  {
    name: 'Henry Moore',
    email: 'henry.moore@email.com',
    phone: '+1-555-0208',
    address: '258 Spruce Avenue, San Diego, CA 92101',
    organizationDomain: 'umbrella.com',
    status: CustomerStatus.ACTIVE,
    notes: 'Group organizer, books for large parties',
  },
  {
    name: 'Iris Taylor',
    email: 'iris.taylor@email.com',
    phone: '+1-555-0209',
    address: '369 Willow Road, Dallas, TX 75201',
    organizationDomain: 'acme.com',
    status: CustomerStatus.ACTIVE,
    notes: 'Honeymoon specialist, books romantic getaways',
  },
  {
    name: 'Jack Anderson',
    email: 'jack.anderson@email.com',
    phone: '+1-555-0210',
    address: '741 Poplar Street, San Jose, CA 95101',
    organizationDomain: 'globex.co',
    status: CustomerStatus.INACTIVE,
    notes: 'Budget traveler, price-sensitive customer',
  },
  {
    name: 'Karen Thomas',
    email: 'karen.thomas@email.com',
    phone: '+1-555-0211',
    address: '852 Ash Lane, Austin, TX 78701',
    organizationDomain: 'initech.org',
    status: CustomerStatus.ACTIVE,
    notes: 'Cultural tourism enthusiast',
  },
  {
    name: 'Larry Jackson',
    email: 'larry.jackson@email.com',
    phone: '+1-555-0212',
    address: '963 Hickory Drive, Jacksonville, FL 32201',
    organizationDomain: 'umbrella.com',
    status: CustomerStatus.PENDING,
    notes: 'New customer, interested in beach destinations',
  },
  {
    name: 'Mary White',
    email: 'mary.white@email.com',
    phone: '+1-555-0213',
    address: '159 Sycamore Avenue, Fort Worth, TX 76101',
    organizationDomain: 'acme.com',
    status: CustomerStatus.ACTIVE,
    notes: 'Solo traveler, prefers guided tours',
  },
  {
    name: 'Nick Harris',
    email: 'nick.harris@email.com',
    phone: '+1-555-0214',
    address: '357 Chestnut Street, Columbus, OH 43201',
    organizationDomain: 'globex.co',
    status: CustomerStatus.ACTIVE,
    notes: 'Photography enthusiast, books scenic destinations',
  },
  {
    name: 'Olivia Martin',
    email: 'olivia.martin@email.com',
    phone: '+1-555-0215',
    address: '468 Walnut Road, Charlotte, NC 28201',
    organizationDomain: 'initech.org',
    status: CustomerStatus.INACTIVE,
    notes: 'Seasonal traveler, books during holidays',
  },
  {
    name: 'Paul Thompson',
    email: 'paul.thompson@email.com',
    phone: '+1-555-0216',
    address: '579 Cherry Lane, Seattle, WA 98101',
    organizationDomain: 'umbrella.com',
    status: CustomerStatus.ACTIVE,
    notes: 'Outdoor adventure seeker',
  },
  {
    name: 'Quinn Garcia',
    email: 'quinn.garcia@email.com',
    phone: '+1-555-0217',
    address: '680 Dogwood Street, Denver, CO 80201',
    organizationDomain: 'acme.com',
    status: CustomerStatus.PENDING,
    notes: 'Wellness traveler, interested in spa packages',
  },
  {
    name: 'Rachel Martinez',
    email: 'rachel.martinez@email.com',
    phone: '+1-555-0218',
    address: '791 Magnolia Avenue, Washington, DC 20001',
    organizationDomain: 'globex.co',
    status: CustomerStatus.ACTIVE,
    notes: 'Educational travel for children',
  },
  {
    name: 'Steve Robinson',
    email: 'steve.robinson@email.com',
    phone: '+1-555-0219',
    address: '802 Redwood Drive, Boston, MA 02101',
    organizationDomain: 'initech.org',
    status: CustomerStatus.ACTIVE,
    notes: 'Wine and food tourism enthusiast',
  },
  {
    name: 'Tina Clark',
    email: 'tina.clark@email.com',
    phone: '+1-555-0220',
    address: '913 Sequoia Road, Nashville, TN 37201',
    organizationDomain: 'umbrella.com',
    status: CustomerStatus.INACTIVE,
    notes: 'Music festival traveler',
  },
];
