import { Gender } from '../entity/customer.entity';

export const customers = [
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    middleName: 'Marie',
    dateOfBirth: '1985-03-15',
    gender: Gender.FEMALE,
    email: 'alice.johnson@email.com',
    phone: '+1-555-0201',
    alternativePhone: '+1-555-0201-alt',
    address: '123 Main Street, New York, NY 10001',
    emergencyContactName: 'John Johnson',
    emergencyContactPhone: '+1-555-0201-emergency',
    emergencyContactRelation: 'Spouse',
    passportNumber: 'A12345678',
    passportExpiryDate: '2030-03-15',
    passportIssueDate: '2020-03-15',
    passportCountry: 'United States',
    voterId: 'VOTER123456',
    aadhaarId: '1234-5678-9012',
    relatives: [
      {
        name: 'John Johnson',
        relation: 'Spouse',
        phone: '+1-555-0201-spouse',
        address: '123 Main Street, New York, NY 10001',
      },
      {
        name: 'Sarah Johnson',
        relation: 'Daughter',
        phone: '+1-555-0201-daughter',
        address: '123 Main Street, New York, NY 10001',
      },
    ],
    dietaryRestrictions: 'Vegetarian, no nuts',
    medicalConditions: 'Mild asthma',
    specialRequests: 'Ground floor room preferred',
    notes: 'Regular customer, prefers luxury accommodations',
    organizationDomain: 'acme.com',
    profilePhoto: 'alice_johnson_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Bob',
    lastName: 'Smith',
    middleName: 'James',
    dateOfBirth: '1982-07-22',
    gender: Gender.MALE,
    email: 'bob.smith@email.com',
    phone: '+1-555-0202',
    alternativePhone: '+1-555-0202-alt',
    address: '456 Oak Avenue, Los Angeles, CA 90210',
    emergencyContactName: 'Lisa Smith',
    emergencyContactPhone: '+1-555-0202-emergency',
    emergencyContactRelation: 'Sister',
    passportNumber: 'B98765432',
    passportExpiryDate: '2029-07-22',
    passportIssueDate: '2019-07-22',
    passportCountry: 'United States',
    voterId: 'VOTER987654',
    aadhaarId: '9876-5432-1098',
    relatives: [
      {
        name: 'Lisa Smith',
        relation: 'Sister',
        phone: '+1-555-0202-sister',
        address: '789 Pine Street, San Francisco, CA 94101',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Adventure activities preferred',
    notes: 'Adventure enthusiast, interested in extreme sports',
    organizationDomain: 'globex.co',
    profilePhoto: 'bob_smith_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Carol',
    lastName: 'Williams',
    middleName: 'Ann',
    dateOfBirth: '1990-11-08',
    gender: Gender.FEMALE,
    email: 'carol.williams@email.com',
    phone: '+1-555-0203',
    alternativePhone: '+1-555-0203-alt',
    address: '789 Pine Road, Chicago, IL 60601',
    emergencyContactName: 'Michael Williams',
    emergencyContactPhone: '+1-555-0203-emergency',
    emergencyContactRelation: 'Brother',
    passportNumber: 'C45678901',
    passportExpiryDate: '2028-11-08',
    passportIssueDate: '2018-11-08',
    passportCountry: 'United States',
    voterId: 'VOTER456789',
    aadhaarId: '4567-8901-2345',
    relatives: [
      {
        name: 'Michael Williams',
        relation: 'Brother',
        phone: '+1-555-0203-brother',
        address: '321 Oak Street, Detroit, MI 48201',
      },
    ],
    dietaryRestrictions: 'Gluten-free',
    medicalConditions: 'None',
    specialRequests: 'Need guidance on package selection',
    notes: 'First-time customer, needs guidance on package selection',
    organizationDomain: 'initech.org',
    profilePhoto: 'carol_williams_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'David',
    lastName: 'Brown',
    middleName: 'Robert',
    dateOfBirth: '1978-05-12',
    gender: Gender.MALE,
    email: 'david.brown@email.com',
    phone: '+1-555-0204',
    alternativePhone: '+1-555-0204-alt',
    address: '321 Elm Street, Houston, TX 77001',
    emergencyContactName: 'Jennifer Brown',
    emergencyContactPhone: '+1-555-0204-emergency',
    emergencyContactRelation: 'Wife',
    passportNumber: 'D78901234',
    passportExpiryDate: '2031-05-12',
    passportIssueDate: '2021-05-12',
    passportCountry: 'United States',
    voterId: 'VOTER789012',
    aadhaarId: '7890-1234-5678',
    relatives: [
      {
        name: 'Jennifer Brown',
        relation: 'Wife',
        phone: '+1-555-0204-wife',
        address: '321 Elm Street, Houston, TX 77001',
      },
      {
        name: 'Emma Brown',
        relation: 'Daughter',
        phone: '+1-555-0204-daughter',
        address: '321 Elm Street, Houston, TX 77001',
      },
      {
        name: 'James Brown',
        relation: 'Son',
        phone: '+1-555-0204-son',
        address: '321 Elm Street, Houston, TX 77001',
      },
    ],
    dietaryRestrictions: 'Family-friendly meals',
    medicalConditions: 'None',
    specialRequests: 'Child-friendly accommodations',
    notes: 'Family traveler with young children',
    organizationDomain: 'umbrella.com',
    profilePhoto: 'david_brown_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Eva',
    lastName: 'Davis',
    middleName: 'Grace',
    dateOfBirth: '1975-12-03',
    gender: Gender.FEMALE,
    email: 'eva.davis@email.com',
    phone: '+1-555-0205',
    alternativePhone: '+1-555-0205-alt',
    address: '654 Maple Drive, Phoenix, AZ 85001',
    emergencyContactName: 'Robert Davis',
    emergencyContactPhone: '+1-555-0205-emergency',
    emergencyContactRelation: 'Husband',
    passportNumber: 'E01234567',
    passportExpiryDate: '2027-12-03',
    passportIssueDate: '2017-12-03',
    passportCountry: 'United States',
    voterId: 'VOTER012345',
    aadhaarId: '0123-4567-8901',
    relatives: [
      {
        name: 'Robert Davis',
        relation: 'Husband',
        phone: '+1-555-0205-husband',
        address: '654 Maple Drive, Phoenix, AZ 85001',
      },
    ],
    dietaryRestrictions: 'Low sodium diet',
    medicalConditions: 'High blood pressure',
    specialRequests: 'Quiet accommodations preferred',
    notes: 'Inactive customer, last booking was 6 months ago',
    organizationDomain: 'acme.com',
    profilePhoto: 'eva_davis_profile.jpeg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Frank',
    lastName: 'Miller',
    middleName: 'Thomas',
    dateOfBirth: '1980-09-18',
    gender: Gender.MALE,
    email: 'frank.miller@email.com',
    phone: '+1-555-0206',
    alternativePhone: '+1-555-0206-alt',
    address: '987 Cedar Lane, Philadelphia, PA 19101',
    emergencyContactName: 'Susan Miller',
    emergencyContactPhone: '+1-555-0206-emergency',
    emergencyContactRelation: 'Wife',
    passportNumber: 'F23456789',
    passportExpiryDate: '2029-09-18',
    passportIssueDate: '2019-09-18',
    passportCountry: 'United States',
    voterId: 'VOTER234567',
    aadhaarId: '2345-6789-0123',
    relatives: [
      {
        name: 'Susan Miller',
        relation: 'Wife',
        phone: '+1-555-0206-wife',
        address: '987 Cedar Lane, Philadelphia, PA 19101',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Last-minute booking flexibility needed',
    notes: 'Business traveler, frequently books last-minute trips',
    organizationDomain: 'globex.co',
    profilePhoto: 'frank_miller_profile.webp',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Grace',
    lastName: 'Wilson',
    middleName: 'Elizabeth',
    dateOfBirth: '1965-04-25',
    gender: Gender.FEMALE,
    email: 'grace.wilson@email.com',
    phone: '+1-555-0207',
    alternativePhone: '+1-555-0207-alt',
    address: '147 Birch Street, San Antonio, TX 78201',
    emergencyContactName: 'William Wilson',
    emergencyContactPhone: '+1-555-0207-emergency',
    emergencyContactRelation: 'Son',
    passportNumber: 'G34567890',
    passportExpiryDate: '2028-04-25',
    passportIssueDate: '2018-04-25',
    passportCountry: 'United States',
    voterId: 'VOTER345678',
    aadhaarId: '3456-7890-1234',
    relatives: [
      {
        name: 'William Wilson',
        relation: 'Son',
        phone: '+1-555-0207-son',
        address: '258 Oak Avenue, Austin, TX 78701',
      },
    ],
    dietaryRestrictions: 'Soft foods, no spicy',
    medicalConditions: 'Mobility issues, uses wheelchair',
    specialRequests: 'Accessible accommodations required',
    notes: 'Senior traveler, requires accessible accommodations',
    organizationDomain: 'initech.org',
    profilePhoto: 'grace_wilson_profile.webp',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Henry',
    lastName: 'Moore',
    middleName: 'Charles',
    dateOfBirth: '1972-01-30',
    gender: Gender.MALE,
    email: 'henry.moore@email.com',
    phone: '+1-555-0208',
    alternativePhone: '+1-555-0208-alt',
    address: '258 Spruce Avenue, San Diego, CA 92101',
    emergencyContactName: 'Patricia Moore',
    emergencyContactPhone: '+1-555-0208-emergency',
    emergencyContactRelation: 'Wife',
    passportNumber: 'H45678901',
    passportExpiryDate: '2030-01-30',
    passportIssueDate: '2020-01-30',
    passportCountry: 'United States',
    voterId: 'VOTER456789',
    aadhaarId: '4567-8901-2345',
    relatives: [
      {
        name: 'Patricia Moore',
        relation: 'Wife',
        phone: '+1-555-0208-wife',
        address: '258 Spruce Avenue, San Diego, CA 92101',
      },
      {
        name: 'Robert Moore',
        relation: 'Brother',
        phone: '+1-555-0208-brother',
        address: '369 Pine Street, Los Angeles, CA 90210',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Group booking coordination needed',
    notes: 'Group organizer, books for large parties',
    organizationDomain: 'umbrella.com',
    profilePhoto: 'henry_moore_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Iris',
    lastName: 'Taylor',
    middleName: 'Rose',
    dateOfBirth: '1988-08-14',
    gender: Gender.FEMALE,
    email: 'iris.taylor@email.com',
    phone: '+1-555-0209',
    alternativePhone: '+1-555-0209-alt',
    address: '369 Willow Road, Dallas, TX 75201',
    emergencyContactName: 'Daniel Taylor',
    emergencyContactPhone: '+1-555-0209-emergency',
    emergencyContactRelation: 'Husband',
    passportNumber: 'I56789012',
    passportExpiryDate: '2029-08-14',
    passportIssueDate: '2019-08-14',
    passportCountry: 'United States',
    voterId: 'VOTER567890',
    aadhaarId: '5678-9012-3456',
    relatives: [
      {
        name: 'Daniel Taylor',
        relation: 'Husband',
        phone: '+1-555-0209-husband',
        address: '369 Willow Road, Dallas, TX 75201',
      },
    ],
    dietaryRestrictions: 'Vegetarian',
    medicalConditions: 'None',
    specialRequests: 'Romantic settings, couples activities',
    notes: 'Honeymoon specialist, books romantic getaways',
    organizationDomain: 'acme.com',
    profilePhoto: 'iris_taylor_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Jack',
    lastName: 'Anderson',
    middleName: 'Michael',
    dateOfBirth: '1983-06-10',
    gender: Gender.MALE,
    email: 'jack.anderson@email.com',
    phone: '+1-555-0210',
    alternativePhone: '+1-555-0210-alt',
    address: '741 Poplar Street, San Jose, CA 95101',
    emergencyContactName: 'Sarah Anderson',
    emergencyContactPhone: '+1-555-0210-emergency',
    emergencyContactRelation: 'Sister',
    passportNumber: 'J67890123',
    passportExpiryDate: '2028-06-10',
    passportIssueDate: '2018-06-10',
    passportCountry: 'United States',
    voterId: 'VOTER678901',
    aadhaarId: '6789-0123-4567',
    relatives: [
      {
        name: 'Sarah Anderson',
        relation: 'Sister',
        phone: '+1-555-0210-sister',
        address: '852 Oak Street, San Francisco, CA 94101',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Budget-friendly options preferred',
    notes: 'Budget traveler, price-sensitive customer',
    organizationDomain: 'globex.co',
    profilePhoto: 'jack_anderson_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Karen',
    lastName: 'Thomas',
    middleName: 'Susan',
    dateOfBirth: '1976-02-28',
    gender: Gender.FEMALE,
    email: 'karen.thomas@email.com',
    phone: '+1-555-0211',
    alternativePhone: '+1-555-0211-alt',
    address: '852 Ash Lane, Austin, TX 78701',
    emergencyContactName: 'Mark Thomas',
    emergencyContactPhone: '+1-555-0211-emergency',
    emergencyContactRelation: 'Husband',
    passportNumber: 'K78901234',
    passportExpiryDate: '2031-02-28',
    passportIssueDate: '2021-02-28',
    passportCountry: 'United States',
    voterId: 'VOTER789012',
    aadhaarId: '7890-1234-5678',
    relatives: [
      {
        name: 'Mark Thomas',
        relation: 'Husband',
        phone: '+1-555-0211-husband',
        address: '852 Ash Lane, Austin, TX 78701',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Cultural sites and museums preferred',
    notes: 'Cultural tourism enthusiast',
    organizationDomain: 'initech.org',
    profilePhoto: 'karen_thomas_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Larry',
    lastName: 'Jackson',
    middleName: 'David',
    dateOfBirth: '1991-10-05',
    gender: Gender.MALE,
    email: 'larry.jackson@email.com',
    phone: '+1-555-0212',
    alternativePhone: '+1-555-0212-alt',
    address: '963 Hickory Drive, Jacksonville, FL 32201',
    emergencyContactName: 'Jennifer Jackson',
    emergencyContactPhone: '+1-555-0212-emergency',
    emergencyContactRelation: 'Mother',
    passportNumber: 'L89012345',
    passportExpiryDate: '2029-10-05',
    passportIssueDate: '2019-10-05',
    passportCountry: 'United States',
    voterId: 'VOTER890123',
    aadhaarId: '8901-2345-6789',
    relatives: [
      {
        name: 'Jennifer Jackson',
        relation: 'Mother',
        phone: '+1-555-0212-mother',
        address: '147 Pine Street, Miami, FL 33101',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Beach destinations preferred',
    notes: 'New customer, interested in beach destinations',
    organizationDomain: 'umbrella.com',
    profilePhoto: 'larry_jackson_profile.webp',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Mary',
    lastName: 'White',
    middleName: 'Jane',
    dateOfBirth: '1987-12-12',
    gender: Gender.FEMALE,
    email: 'mary.white@email.com',
    phone: '+1-555-0213',
    alternativePhone: '+1-555-0213-alt',
    address: '159 Sycamore Avenue, Fort Worth, TX 76101',
    emergencyContactName: 'Robert White',
    emergencyContactPhone: '+1-555-0213-emergency',
    emergencyContactRelation: 'Brother',
    passportNumber: 'M90123456',
    passportExpiryDate: '2030-12-12',
    passportIssueDate: '2020-12-12',
    passportCountry: 'United States',
    voterId: 'VOTER901234',
    aadhaarId: '9012-3456-7890',
    relatives: [
      {
        name: 'Robert White',
        relation: 'Brother',
        phone: '+1-555-0213-brother',
        address: '258 Elm Street, Dallas, TX 75201',
      },
    ],
    dietaryRestrictions: 'Vegetarian',
    medicalConditions: 'None',
    specialRequests: 'Guided tours and group activities preferred',
    notes: 'Solo traveler, prefers guided tours',
    organizationDomain: 'acme.com',
    profilePhoto: 'mary_white_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Nick',
    lastName: 'Harris',
    middleName: 'Alexander',
    dateOfBirth: '1984-03-20',
    gender: Gender.MALE,
    email: 'nick.harris@email.com',
    phone: '+1-555-0214',
    alternativePhone: '+1-555-0214-alt',
    address: '357 Chestnut Street, Columbus, OH 43201',
    emergencyContactName: 'Lisa Harris',
    emergencyContactPhone: '+1-555-0214-emergency',
    emergencyContactRelation: 'Wife',
    passportNumber: 'N01234567',
    passportExpiryDate: '2029-03-20',
    passportIssueDate: '2019-03-20',
    passportCountry: 'United States',
    voterId: 'VOTER012345',
    aadhaarId: '0123-4567-8901',
    relatives: [
      {
        name: 'Lisa Harris',
        relation: 'Wife',
        phone: '+1-555-0214-wife',
        address: '357 Chestnut Street, Columbus, OH 43201',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Scenic locations for photography',
    notes: 'Photography enthusiast, books scenic destinations',
    organizationDomain: 'globex.co',
    profilePhoto: 'nick_harris_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Olivia',
    lastName: 'Martin',
    middleName: 'Grace',
    dateOfBirth: '1979-11-15',
    gender: Gender.FEMALE,
    email: 'olivia.martin@email.com',
    phone: '+1-555-0215',
    alternativePhone: '+1-555-0215-alt',
    address: '468 Walnut Road, Charlotte, NC 28201',
    emergencyContactName: 'James Martin',
    emergencyContactPhone: '+1-555-0215-emergency',
    emergencyContactRelation: 'Husband',
    passportNumber: 'O12345678',
    passportExpiryDate: '2027-11-15',
    passportIssueDate: '2017-11-15',
    passportCountry: 'United States',
    voterId: 'VOTER123456',
    aadhaarId: '1234-5678-9012',
    relatives: [
      {
        name: 'James Martin',
        relation: 'Husband',
        phone: '+1-555-0215-husband',
        address: '468 Walnut Road, Charlotte, NC 28201',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Holiday season bookings preferred',
    notes: 'Seasonal traveler, books during holidays',
    organizationDomain: 'initech.org',
    profilePhoto: 'olivia_martin_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Paul',
    lastName: 'Thompson',
    middleName: 'Edward',
    dateOfBirth: '1986-07-08',
    gender: Gender.MALE,
    email: 'paul.thompson@email.com',
    phone: '+1-555-0216',
    alternativePhone: '+1-555-0216-alt',
    address: '579 Cherry Lane, Seattle, WA 98101',
    emergencyContactName: 'Amanda Thompson',
    emergencyContactPhone: '+1-555-0216-emergency',
    emergencyContactRelation: 'Wife',
    passportNumber: 'P23456789',
    passportExpiryDate: '2031-07-08',
    passportIssueDate: '2021-07-08',
    passportCountry: 'United States',
    voterId: 'VOTER234567',
    aadhaarId: '2345-6789-0123',
    relatives: [
      {
        name: 'Amanda Thompson',
        relation: 'Wife',
        phone: '+1-555-0216-wife',
        address: '579 Cherry Lane, Seattle, WA 98101',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Outdoor adventure activities',
    notes: 'Outdoor adventure seeker',
    organizationDomain: 'umbrella.com',
    profilePhoto: 'paul_thompson_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Quinn',
    lastName: 'Garcia',
    middleName: 'Isabella',
    dateOfBirth: '1993-05-03',
    gender: Gender.FEMALE,
    email: 'quinn.garcia@email.com',
    phone: '+1-555-0217',
    alternativePhone: '+1-555-0217-alt',
    address: '680 Dogwood Street, Denver, CO 80201',
    emergencyContactName: 'Carlos Garcia',
    emergencyContactPhone: '+1-555-0217-emergency',
    emergencyContactRelation: 'Father',
    passportNumber: 'Q34567890',
    passportExpiryDate: '2028-05-03',
    passportIssueDate: '2018-05-03',
    passportCountry: 'United States',
    voterId: 'VOTER345678',
    aadhaarId: '3456-7890-1234',
    relatives: [
      {
        name: 'Carlos Garcia',
        relation: 'Father',
        phone: '+1-555-0217-father',
        address: '791 Oak Street, Boulder, CO 80301',
      },
    ],
    dietaryRestrictions: 'Organic, plant-based',
    medicalConditions: 'None',
    specialRequests: 'Wellness and spa packages preferred',
    notes: 'Wellness traveler, interested in spa packages',
    organizationDomain: 'acme.com',
    profilePhoto: 'quinn_garcia_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Rachel',
    lastName: 'Martinez',
    middleName: 'Nicole',
    dateOfBirth: '1981-09-25',
    gender: Gender.FEMALE,
    email: 'rachel.martinez@email.com',
    phone: '+1-555-0218',
    alternativePhone: '+1-555-0218-alt',
    address: '791 Magnolia Avenue, Washington, DC 20001',
    emergencyContactName: 'David Martinez',
    emergencyContactPhone: '+1-555-0218-emergency',
    emergencyContactRelation: 'Husband',
    passportNumber: 'R45678901',
    passportExpiryDate: '2030-09-25',
    passportIssueDate: '2020-09-25',
    passportCountry: 'United States',
    voterId: 'VOTER456789',
    aadhaarId: '4567-8901-2345',
    relatives: [
      {
        name: 'David Martinez',
        relation: 'Husband',
        phone: '+1-555-0218-husband',
        address: '791 Magnolia Avenue, Washington, DC 20001',
      },
      {
        name: 'Sophia Martinez',
        relation: 'Daughter',
        phone: '+1-555-0218-daughter',
        address: '791 Magnolia Avenue, Washington, DC 20001',
      },
    ],
    dietaryRestrictions: 'Family-friendly meals',
    medicalConditions: 'None',
    specialRequests: 'Educational activities for children',
    notes: 'Educational travel for children',
    organizationDomain: 'globex.co',
    profilePhoto: 'rachel_martinez_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Steve',
    lastName: 'Robinson',
    middleName: 'William',
    dateOfBirth: '1974-01-18',
    gender: Gender.MALE,
    email: 'steve.robinson@email.com',
    phone: '+1-555-0219',
    alternativePhone: '+1-555-0219-alt',
    address: '802 Redwood Drive, Boston, MA 02101',
    emergencyContactName: 'Linda Robinson',
    emergencyContactPhone: '+1-555-0219-emergency',
    emergencyContactRelation: 'Wife',
    passportNumber: 'S56789012',
    passportExpiryDate: '2029-01-18',
    passportIssueDate: '2019-01-18',
    passportCountry: 'United States',
    voterId: 'VOTER567890',
    aadhaarId: '5678-9012-3456',
    relatives: [
      {
        name: 'Linda Robinson',
        relation: 'Wife',
        phone: '+1-555-0219-wife',
        address: '802 Redwood Drive, Boston, MA 02101',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Wine tasting and culinary experiences',
    notes: 'Wine and food tourism enthusiast',
    organizationDomain: 'initech.org',
    profilePhoto: 'steve_robinson_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
  {
    firstName: 'Tina',
    lastName: 'Clark',
    middleName: 'Michelle',
    dateOfBirth: '1989-04-30',
    gender: Gender.FEMALE,
    email: 'tina.clark@email.com',
    phone: '+1-555-0220',
    alternativePhone: '+1-555-0220-alt',
    address: '913 Sequoia Road, Nashville, TN 37201',
    emergencyContactName: 'Brian Clark',
    emergencyContactPhone: '+1-555-0220-emergency',
    emergencyContactRelation: 'Brother',
    passportNumber: 'T67890123',
    passportExpiryDate: '2028-04-30',
    passportIssueDate: '2018-04-30',
    passportCountry: 'United States',
    voterId: 'VOTER678901',
    aadhaarId: '6789-0123-4567',
    relatives: [
      {
        name: 'Brian Clark',
        relation: 'Brother',
        phone: '+1-555-0220-brother',
        address: '147 Maple Street, Memphis, TN 38101',
      },
    ],
    dietaryRestrictions: 'No dietary restrictions',
    medicalConditions: 'None',
    specialRequests: 'Music festival destinations',
    notes: 'Music festival traveler',
    organizationDomain: 'umbrella.com',
    profilePhoto: 'tina_clark_profile.jpg',
    passportPhotos: ['passport_page1.jpg', 'passport_page2.jpg'],
    voterIdPhotos: ['voter_id.jpeg'],
    aadhaarIdPhotos: ['aadhaar_front.png', 'aadhaar_back.png'],
  },
];
