import { EmployeeStatus } from '../entity/employee.entity';

export const additionalEmployees = [
  // Acme Corp employees
  {
    name: 'Sarah Wilson',
    email: 'sarah.wilson@acme.com',
    phone: '+1-555-1235',
    address: '123 Tech Street, San Francisco, CA',
    experience: '5 years',
    specialization: 'Software Development',
    dateOfBirth: '1990-03-15',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'acme.com',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'Michael Chen',
    email: 'michael.chen@acme.com',
    phone: '+1-555-1236',
    address: '456 Innovation Ave, San Francisco, CA',
    experience: '3 years',
    specialization: 'Product Management',
    dateOfBirth: '1988-07-22',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'acme.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@acme.com',
    phone: '+1-555-1237',
    address: '789 Startup Blvd, San Francisco, CA',
    experience: '2 years',
    specialization: 'UI/UX Design',
    dateOfBirth: '1992-11-08',
    gender: 'Female',
    nationality: 'Mexican',
    maritalStatus: 'Single',
    organizationDomain: 'acme.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },

  // Globex Inc employees
  {
    name: 'James Thompson',
    email: 'james.thompson@globex.co',
    phone: '+1-555-5679',
    address: '321 Finance Plaza, New York, NY',
    experience: '8 years',
    specialization: 'Financial Analysis',
    dateOfBirth: '1985-01-12',
    gender: 'Male',
    nationality: 'British',
    maritalStatus: 'Married',
    organizationDomain: 'globex.co',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'Lisa Park',
    email: 'lisa.park@globex.co',
    phone: '+1-555-5680',
    address: '654 Investment St, New York, NY',
    experience: '4 years',
    specialization: 'Risk Management',
    dateOfBirth: '1989-09-30',
    gender: 'Female',
    nationality: 'Korean',
    maritalStatus: 'Single',
    organizationDomain: 'globex.co',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'David Kumar',
    email: 'david.kumar@globex.co',
    phone: '+1-555-5681',
    address: '987 Trading Ave, New York, NY',
    experience: '6 years',
    specialization: 'Investment Banking',
    dateOfBirth: '1987-05-18',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Married',
    organizationDomain: 'globex.co',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },

  // Initech employees
  {
    name: 'Jennifer Lee',
    email: 'jennifer.lee@initech.org',
    phone: '+1-555-9013',
    address: '147 Software Lane, Austin, TX',
    experience: '7 years',
    specialization: 'Backend Development',
    dateOfBirth: '1986-12-03',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'initech.org',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'Robert Martinez',
    email: 'robert.martinez@initech.org',
    phone: '+1-555-9014',
    address: '258 Code Street, Austin, TX',
    experience: '3 years',
    specialization: 'DevOps',
    dateOfBirth: '1991-08-14',
    gender: 'Male',
    nationality: 'Mexican',
    maritalStatus: 'Single',
    organizationDomain: 'initech.org',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },

  // Umbrella Corp employees
  {
    name: 'Dr. Amanda Foster',
    email: 'amanda.foster@umbrella.com',
    phone: '+1-555-3457',
    address: '369 Research Center, Boston, MA',
    experience: '12 years',
    specialization: 'Biotechnology Research',
    dateOfBirth: '1980-04-25',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'umbrella.com',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'Dr. Kevin Zhang',
    email: 'kevin.zhang@umbrella.com',
    phone: '+1-555-3458',
    address: '741 Lab Complex, Boston, MA',
    experience: '9 years',
    specialization: 'Pharmaceutical Development',
    dateOfBirth: '1983-10-11',
    gender: 'Male',
    nationality: 'Chinese',
    maritalStatus: 'Single',
    organizationDomain: 'umbrella.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'Dr. Maria Santos',
    email: 'maria.santos@umbrella.com',
    phone: '+1-555-3459',
    address: '852 Innovation Hub, Boston, MA',
    experience: '6 years',
    specialization: 'Clinical Research',
    dateOfBirth: '1988-06-07',
    gender: 'Female',
    nationality: 'Brazilian',
    maritalStatus: 'Married',
    organizationDomain: 'umbrella.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },
  {
    name: 'Dr. Thomas Anderson',
    email: 'thomas.anderson@umbrella.com',
    phone: '+1-555-3460',
    address: '963 Science Park, Boston, MA',
    experience: '4 years',
    specialization: 'Molecular Biology',
    dateOfBirth: '1990-02-19',
    gender: 'Male',
    nationality: 'Canadian',
    maritalStatus: 'Single',
    organizationDomain: 'umbrella.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
  },
];
