import { EmployeeStatus } from '../entity/employee.entity';

export const additionalEmployees = [
  // Acme Corp employees
  {
    name: 'Sarah Wilson',
    email: 'sarah.wilson@acme.com',
    phone: '+1-555-1235',
    address: '123 Tech Street, San Francisco, CA',
    experience: '5 years',
    specialization: 'Software Development',
    dateOfBirth: '1990-03-15',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'acme.com',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/a6309c5a-8f07-44d6-b21a-96f3a684ab3b/carol_williams_profile.jpg',
  },
  {
    name: 'Michael Chen',
    email: 'michael.chen@acme.com',
    phone: '+1-555-1236',
    address: '456 Innovation Ave, San Francisco, CA',
    experience: '3 years',
    specialization: 'Product Management',
    dateOfBirth: '1988-07-22',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'acme.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/046bd4c8-894d-4e29-84ac-852dd34c133b/bob_smith_profile.jpg',
  },
  {
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@acme.com',
    phone: '+1-555-1237',
    address: '789 Startup Blvd, San Francisco, CA',
    experience: '2 years',
    specialization: 'UI/UX Design',
    dateOfBirth: '1992-11-08',
    gender: 'Female',
    nationality: 'Mexican',
    maritalStatus: 'Single',
    organizationDomain: 'acme.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/c70c0c05-46fc-44fb-8475-6d4681d5d2a9/alice_johnson_profile.jpg',
  },

  // Globex Inc employees
  {
    name: 'James Thompson',
    email: 'james.thompson@globex.co',
    phone: '+1-555-5679',
    address: '321 Finance Plaza, New York, NY',
    experience: '8 years',
    specialization: 'Financial Analysis',
    dateOfBirth: '1985-01-12',
    gender: 'Male',
    nationality: 'British',
    maritalStatus: 'Married',
    organizationDomain: 'globex.co',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/7746ee5d-bdad-4c0e-a294-72c2006ff846/rachel_martinez_profile.jpg',
  },
  {
    name: 'Lisa Park',
    email: 'lisa.park@globex.co',
    phone: '+1-555-5680',
    address: '654 Investment St, New York, NY',
    experience: '4 years',
    specialization: 'Risk Management',
    dateOfBirth: '1989-09-30',
    gender: 'Female',
    nationality: 'Korean',
    maritalStatus: 'Single',
    organizationDomain: 'globex.co',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/1079bb7c-f547-459e-bec4-49ea3a27fdd6/nick_harris_profile.jpg',
  },
  {
    name: 'David Kumar',
    email: 'david.kumar@globex.co',
    phone: '+1-555-5681',
    address: '987 Trading Ave, New York, NY',
    experience: '6 years',
    specialization: 'Investment Banking',
    dateOfBirth: '1987-05-18',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Married',
    organizationDomain: 'globex.co',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/7c01d9fb-4f01-4fc0-991a-c8185f1b4eb3/steve_robinson_profile.jpg',
  },

  // Initech employees
  {
    name: 'Jennifer Lee',
    email: 'jennifer.lee@initech.org',
    phone: '+1-555-9013',
    address: '147 Software Lane, Austin, TX',
    experience: '7 years',
    specialization: 'Backend Development',
    dateOfBirth: '1986-12-03',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'initech.org',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/672af04e-d51f-4fc2-8406-88c502dc6037/quinn_garcia_profile.jpg',
  },
  {
    name: 'Robert Martinez',
    email: 'robert.martinez@initech.org',
    phone: '+1-555-9014',
    address: '258 Code Street, Austin, TX',
    experience: '3 years',
    specialization: 'DevOps',
    dateOfBirth: '1991-08-14',
    gender: 'Male',
    nationality: 'Mexican',
    maritalStatus: 'Single',
    organizationDomain: 'initech.org',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/5ce6c737-2396-48c2-86bc-2ccd6f7fa8aa/tina_clark_profile.jpg',
  },

  // Umbrella Corp employees
  {
    name: 'Dr. Amanda Foster',
    email: 'amanda.foster@umbrella.com',
    phone: '+1-555-3457',
    address: '369 Research Center, Boston, MA',
    experience: '12 years',
    specialization: 'Biotechnology Research',
    dateOfBirth: '1980-04-25',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'umbrella.com',
    roleName: 'manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/15fcb6f9-f0ab-44b9-8e9f-3c287a8726a5/olivia_martin_profile.jpg',
  },
  {
    name: 'Dr. Kevin Zhang',
    email: 'kevin.zhang@umbrella.com',
    phone: '+1-555-3458',
    address: '741 Lab Complex, Boston, MA',
    experience: '9 years',
    specialization: 'Pharmaceutical Development',
    dateOfBirth: '1983-10-11',
    gender: 'Male',
    nationality: 'Chinese',
    maritalStatus: 'Single',
    organizationDomain: 'umbrella.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/640657d1-0352-4d56-95e8-42f3cfbd58e9/larry_jackson_profile.webp',
  },
  {
    name: 'Dr. Maria Santos',
    email: 'maria.santos@umbrella.com',
    phone: '+1-555-3459',
    address: '852 Innovation Hub, Boston, MA',
    experience: '6 years',
    specialization: 'Clinical Research',
    dateOfBirth: '1988-06-07',
    gender: 'Female',
    nationality: 'Brazilian',
    maritalStatus: 'Married',
    organizationDomain: 'umbrella.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/b0f03164-690d-4666-b9df-7e8485054086/eva_davis_profile.jpeg',
  },
  {
    name: 'Dr. Thomas Anderson',
    email: 'thomas.anderson@umbrella.com',
    phone: '+1-555-3460',
    address: '963 Science Park, Boston, MA',
    experience: '4 years',
    specialization: 'Molecular Biology',
    dateOfBirth: '1990-02-19',
    gender: 'Male',
    nationality: 'Canadian',
    maritalStatus: 'Single',
    organizationDomain: 'umbrella.com',
    roleName: 'employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/a9e71203-1885-4835-ae76-70ec008ef191/grace_wilson_profile.webp',
  },

  // Finance Team
  {
    name: 'Mike Finance',
    email: 'mike.finance@acme.com',
    phone: '+1-555-0001',
    address: '100 Money Lane, San Francisco, CA',
    experience: '10 years',
    specialization: 'Accounting',
    dateOfBirth: '1982-05-20',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'acme.com',
    roleName: 'finance_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/3957a204-072f-457e-ae85-0ff474c187d4/mary_white_profile.jpg',
  },
  {
    name: 'Kate Ledger',
    email: 'kate.ledger@initech.org',
    phone: '+1-555-0002',
    address: '200 Tax Blvd, Austin, TX',
    experience: '4 years',
    specialization: 'Bookkeeping',
    dateOfBirth: '1991-09-15',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'initech.org',
    roleName: 'finance_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/3957a204-072f-457e-ae85-0ff474c187d4/mary_white_profile.jpg',
  },

  // Booking Team
  {
    name: 'Linda Reserve',
    email: 'linda.reserve@acme.com',
    phone: '+1-555-0003',
    address: '300 Travel St, San Francisco, CA',
    experience: '6 years',
    specialization: 'Customer Service',
    dateOfBirth: '1987-11-10',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'acme.com',
    roleName: 'booking_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/3f80ea44-3907-4058-b80e-ae7f5bbc8b00/frank_miller_profile.webp',
  },
  {
    name: 'John Booking',
    email: 'john.booking@globex.co',
    phone: '+1-555-0004',
    address: '400 Plaza Way, New York, NY',
    experience: '8 years',
    specialization: 'Hospitality',
    dateOfBirth: '1984-03-25',
    gender: 'Male',
    nationality: 'British',
    maritalStatus: 'Single',
    organizationDomain: 'globex.co',
    roleName: 'booking_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/586541e4-6720-4085-b8a6-769937ccd379/karen_thomas_profile.jpg',
  },

  // Leads Team
  {
    name: 'Sara Sales',
    email: 'sara.sales@globex.co',
    phone: '+1-555-0005',
    address: '500 Market Ave, New York, NY',
    experience: '5 years',
    specialization: 'Sales',
    dateOfBirth: '1992-06-12',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'globex.co',
    roleName: 'leads_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/54280275-62c8-4d32-ad55-eaf8857a8969/iris_taylor_profile.jpg',
  },
  {
    name: 'Becky Lead',
    email: 'becky.lead@umbrella.com',
    phone: '+1-555-0006',
    address: '600 Biotech Rd, Boston, MA',
    experience: '7 years',
    specialization: 'Marketing',
    dateOfBirth: '1989-12-01',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'umbrella.com',
    roleName: 'leads_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/4de58862-96e6-47e0-9e13-e3953559c64d/henry_moore_profile.jpg',
  },

  // Operations Team
  {
    name: 'Steve Ops',
    email: 'steve.ops@umbrella.com',
    phone: '+1-555-0007',
    address: '700 Logistic Cir, Boston, MA',
    experience: '6 years',
    specialization: 'Supply Chain',
    dateOfBirth: '1988-08-18',
    gender: 'Male',
    nationality: 'Canadian',
    maritalStatus: 'Single',
    organizationDomain: 'umbrella.com',
    roleName: 'operations_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/47da31ea-aa11-4624-90d5-64e3d9f8feac/david_brown_profile.jpg',
  },
  {
    name: 'John Logistics',
    email: 'john.logistics@globex.co',
    phone: '+1-555-0008',
    address: '800 Cargo Way, New York, NY',
    experience: '12 years',
    specialization: 'Operations',
    dateOfBirth: '1980-01-30',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'globex.co',
    roleName: 'operations_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/47da31ea-aa11-4624-90d5-64e3d9f8feac/david_brown_profile.jpg',
  },

  // Acme Corp Team Expansion
  {
    name: 'Alice Finance',
    email: 'alice.finance@acme.com',
    phone: '+1-555-0101',
    address: '101 Money Lane, San Francisco, CA',
    experience: '2 years',
    specialization: 'Auditing',
    dateOfBirth: '1995-04-15',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'acme.com',
    roleName: 'finance_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/a6309c5a-8f07-44d6-b21a-96f3a684ab3b/carol_williams_profile.jpg',
  },
  {
    name: 'Bob Finance',
    email: 'bob.finance@acme.com',
    phone: '+1-555-0102',
    address: '102 Money Lane, San Francisco, CA',
    experience: '3 years',
    specialization: 'Taxation',
    dateOfBirth: '1993-08-20',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'acme.com',
    roleName: 'finance_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/046bd4c8-894d-4e29-84ac-852dd34c133b/bob_smith_profile.jpg',
  },
  {
    name: 'Carol Booking',
    email: 'carol.booking@acme.com',
    phone: '+1-555-0103',
    address: '103 Travel St, San Francisco, CA',
    experience: '7 years',
    specialization: 'Tourism',
    dateOfBirth: '1989-12-10',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'acme.com',
    roleName: 'booking_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/c70c0c05-46fc-44fb-8475-6d4681d5d2a9/alice_johnson_profile.jpg',
  },
  {
    name: 'David Reserve',
    email: 'david.reserve@acme.com',
    phone: '+1-555-0104',
    address: '104 Travel St, San Francisco, CA',
    experience: '2 years',
    specialization: 'Ticketing',
    dateOfBirth: '1996-01-05',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'acme.com',
    roleName: 'booking_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/7746ee5d-bdad-4c0e-a294-72c2006ff846/rachel_martinez_profile.jpg',
  },

  // Globex Team Expansion
  {
    name: 'Eve Booking',
    email: 'eve.booking@globex.co',
    phone: '+1-555-0201',
    address: '201 Plaza Way, New York, NY',
    experience: '3 years',
    specialization: 'Customer Support',
    dateOfBirth: '1994-03-30',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'globex.co',
    roleName: 'booking_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/1079bb7c-f547-459e-bec4-49ea3a27fdd6/nick_harris_profile.jpg',
  },
  {
    name: 'Frank Sales',
    email: 'frank.sales@globex.co',
    phone: '+1-555-0202',
    address: '202 Market Ave, New York, NY',
    experience: '9 years',
    specialization: 'Sales Strategy',
    dateOfBirth: '1986-07-15',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'globex.co',
    roleName: 'leads_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/7c01d9fb-4f01-4fc0-991a-c8185f1b4eb3/steve_robinson_profile.jpg',
  },
  {
    name: 'Grace Ops',
    email: 'grace.ops@globex.co',
    phone: '+1-555-0203',
    address: '203 Cargo Way, New York, NY',
    experience: '2 years',
    specialization: 'Warehousing',
    dateOfBirth: '1997-11-22',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'globex.co',
    roleName: 'operations_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/672af04e-d51f-4fc2-8406-88c502dc6037/quinn_garcia_profile.jpg',
  },

  // Initech Team Expansion
  {
    name: 'Hank Finance',
    email: 'hank.finance@initech.org',
    phone: '+1-555-0301',
    address: '301 Tax Blvd, Austin, TX',
    experience: '12 years',
    specialization: 'Treasury',
    dateOfBirth: '1980-02-14',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'initech.org',
    roleName: 'finance_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/2d02d2ff-4d42-46cc-9c13-2a0417a590b5/paul_thompson_profile.jpg',
  },
  {
    name: 'Ivy Ledger',
    email: 'ivy.ledger@initech.org',
    phone: '+1-555-0302',
    address: '302 Tax Blvd, Austin, TX',
    experience: '1 year',
    specialization: 'Accounts Payable',
    dateOfBirth: '1999-06-25',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'initech.org',
    roleName: 'finance_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/5ce6c737-2396-48c2-86bc-2ccd6f7fa8aa/tina_clark_profile.jpg',
  },

  // Umbrella Team Expansion
  {
    name: 'Jack Leads',
    email: 'jack.leads@umbrella.com',
    phone: '+1-555-0401',
    address: '401 Science Park, Boston, MA',
    experience: '3 years',
    specialization: 'Field Sales',
    dateOfBirth: '1994-05-18',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'umbrella.com',
    roleName: 'leads_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/15fcb6f9-f0ab-44b9-8e9f-3c287a8726a5/olivia_martin_profile.jpg',
  },
  {
    name: 'Karen Ops',
    email: 'karen.ops@umbrella.com',
    phone: '+1-555-0402',
    address: '402 Logistic Cir, Boston, MA',
    experience: '15 years',
    specialization: 'Global Logistics',
    dateOfBirth: '1979-10-01',
    gender: 'Female',
    nationality: 'American',
    maritalStatus: 'Married',
    organizationDomain: 'umbrella.com',
    roleName: 'operations_manager',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/15fcb6f9-f0ab-44b9-8e9f-3c287a8726a5/olivia_martin_profile.jpg',
  },
  {
    name: 'Leo Logistics',
    email: 'leo.logistics@umbrella.com',
    phone: '+1-555-0403',
    address: '403 Logistic Cir, Boston, MA',
    experience: '4 years',
    specialization: 'Inventory Control',
    dateOfBirth: '1992-01-30',
    gender: 'Male',
    nationality: 'American',
    maritalStatus: 'Single',
    organizationDomain: 'umbrella.com',
    roleName: 'operations_employee',
    status: EmployeeStatus.ACTIVE,
    profilePhoto:
      'https://20jpaobz2o.ucarecd.net/88219f66-2500-4ff9-abe1-f0fb785e856c/jack_anderson_profile.jpg',
  },
];
