export const leads = [
  {
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+1-555-0101',
    company: 'Tech Solutions Inc.',
    organizationDomain: 'acme.com',
    notes: 'Interested in adventure packages for corporate team building',
    status: 'new' as const,
  },
  {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+1-555-0102',
    company: 'Marketing Pro LLC',
    organizationDomain: 'globex.co',
    notes: 'Looking for family vacation packages to Europe',
    status: 'contacted' as const,
  },
  {
    name: 'Michael Brown',
    email: 'michael.brown@email.com',
    phone: '+1-555-0103',
    company: 'Finance Corp',
    organizationDomain: 'globex.co',
    notes: 'Interested in luxury travel packages',
    status: 'qualified' as const,
  },
  {
    name: 'Emily Davis',
    email: 'emily.davis@email.com',
    phone: '+1-555-0104',
    company: 'Creative Agency',
    organizationDomain: 'acme.com',
    notes: 'Budget-conscious traveler looking for affordable options',
    status: 'new' as const,
  },
  {
    name: 'David Wilson',
    email: 'david.wilson@email.com',
    phone: '+1-555-0105',
    company: 'Consulting Group',
    organizationDomain: 'initech.org',
    notes: 'Solo traveler interested in adventure sports',
    status: 'contacted' as const,
  },
  {
    name: 'Lisa Anderson',
    email: 'lisa.anderson@email.com',
    phone: '+1-555-0106',
    company: 'Healthcare Systems',
    organizationDomain: 'umbrella.com',
    notes: 'Group booking for medical conference attendees',
    status: 'qualified' as const,
  },
  {
    name: 'Robert Taylor',
    email: 'robert.taylor@email.com',
    phone: '+1-555-0107',
    company: 'Real Estate Partners',
    organizationDomain: 'acme.com',
    notes: 'Luxury travel for high-end clients',
    status: 'converted' as const,
  },
  {
    name: 'Jennifer Martinez',
    email: 'jennifer.martinez@email.com',
    phone: '+1-555-0108',
    company: 'Education Foundation',
    organizationDomain: 'globex.co',
    notes: 'Educational travel programs for students',
    status: 'new' as const,
  },
  {
    name: 'Christopher Lee',
    email: 'christopher.lee@email.com',
    phone: '+1-555-0109',
    company: 'Software Development',
    organizationDomain: 'initech.org',
    notes: 'Tech retreat packages for development teams',
    status: 'lost' as const,
  },
  {
    name: 'Amanda White',
    email: 'amanda.white@email.com',
    phone: '+1-555-0110',
    company: 'Event Planning Co.',
    organizationDomain: 'umbrella.com',
    notes: 'Destination wedding packages',
    status: 'qualified' as const,
  },
  {
    name: 'James Thompson',
    email: 'james.thompson@email.com',
    phone: '+1-555-0111',
    company: 'Manufacturing Inc.',
    organizationDomain: 'acme.com',
    notes: 'Corporate incentive travel programs',
    status: 'contacted' as const,
  },
  {
    name: 'Michelle Garcia',
    email: 'michelle.garcia@email.com',
    phone: '+1-555-0112',
    company: 'Retail Chain',
    organizationDomain: 'globex.co',
    notes: 'Employee reward travel packages',
    status: 'new' as const,
  },
  {
    name: 'Kevin Rodriguez',
    email: 'kevin.rodriguez@email.com',
    phone: '+1-555-0113',
    company: 'Sports Management',
    organizationDomain: 'umbrella.com',
    notes: 'Sports team travel arrangements',
    status: 'qualified' as const,
  },
  {
    name: 'Nicole Clark',
    email: 'nicole.clark@email.com',
    phone: '+1-555-0114',
    company: 'Non-Profit Organization',
    organizationDomain: 'initech.org',
    notes: 'Volunteer travel programs',
    status: 'contacted' as const,
  },
  {
    name: 'Daniel Lewis',
    email: 'daniel.lewis@email.com',
    phone: '+1-555-0115',
    company: 'Investment Firm',
    organizationDomain: 'globex.co',
    notes: 'Executive retreat packages',
    status: 'converted' as const,
  },
];
