export const packages = [
  {
    name: 'Himalayan Adventure Trek',
    destination: 'Nepal',
    duration: '14 days',
    price: 2500.0,
    description:
      'Experience the breathtaking beauty of the Himalayas with this 14-day trekking adventure. Journey through remote villages, cross high mountain passes, and witness stunning views of Mount Everest and other iconic peaks.',
    maxGuests: 12,
    category: 'adventure',
    status: 'published',
    thumbnail: 'package-0bfa4e37-4dbd-49f6-bf38-eecd45e31f36-1755551548957.jpg',
    organizationDomain: 'acme.com',
    inclusions: [
      'Professional trekking guide and porters',
      'All meals during the trek',
      'Accommodation in tea houses and lodges',
      'Trekking permits and TIMS card',
      'Airport transfers in Kathmandu',
      'Equipment rental (sleeping bag, trekking poles)',
      'First aid kit and emergency oxygen',
      'Cultural sightseeing in Kathmandu',
    ],
    exclusions: [
      'International flights to/from Kathmandu',
      'Travel insurance',
      'Personal expenses and tips',
      'Alcoholic beverages',
      'Hot showers (available at extra cost)',
      'Charging electronic devices (available at extra cost)',
    ],
  },
  {
    name: 'Cultural Heritage Tour of Rajasthan',
    destination: 'India',
    duration: '10 days',
    price: 1800.0,
    description:
      'Discover the rich cultural heritage of Rajasthan with visits to magnificent palaces, ancient forts, and vibrant markets. Experience traditional music, dance, and cuisine while exploring the royal cities of Jaipur, Udaipur, and Jodhpur.',
    maxGuests: 15,
    category: 'cultural',
    status: 'published',
    thumbnail: 'package-2b5449bb-be53-4652-b0a0-a21ecde2aecf-1758829256858.jpg',
    organizationDomain: 'globex.co',
    inclusions: [
      'Professional tour guide',
      'All accommodation in heritage hotels',
      'All meals (breakfast, lunch, dinner)',
      'Private air-conditioned vehicle',
      'Entrance fees to all monuments',
      'Cultural performances and shows',
      'Camel safari in Jaisalmer',
      'Boat ride on Lake Pichola',
    ],
    exclusions: [
      'International flights to/from India',
      'Visa fees',
      'Travel insurance',
      'Personal expenses and shopping',
      'Alcoholic beverages',
      'Optional activities not mentioned',
    ],
  },
  {
    name: 'Tropical Paradise Getaway',
    destination: 'Maldives',
    duration: '7 days',
    price: 3200.0,
    description:
      'Relax and unwind in the pristine waters of the Maldives. Stay in overwater bungalows, enjoy world-class diving, and experience the ultimate luxury beach vacation with crystal-clear waters and white sandy beaches.',
    maxGuests: 8,
    category: 'luxury',
    status: 'published',
    thumbnail: 'package-2bb106b4-d31b-40c5-be45-6b16ab9dc90d-1758919741729.jpg',
    organizationDomain: 'initech.org',
    inclusions: [
      'Luxury overwater villa accommodation',
      'All meals and beverages',
      'Snorkeling equipment and lessons',
      'Spa treatment (60 minutes)',
      'Sunset dolphin watching cruise',
      'Airport transfers by seaplane',
      'Complimentary WiFi',
      'Daily housekeeping and turndown service',
    ],
    exclusions: [
      'International flights to/from Male',
      'Travel insurance',
      'Additional spa treatments',
      'Scuba diving (available at extra cost)',
      'Water sports activities',
      'Personal expenses and tips',
    ],
  },
  {
    name: 'African Safari Adventure',
    destination: 'Kenya & Tanzania',
    duration: '12 days',
    price: 4500.0,
    description:
      'Embark on an unforgettable safari adventure through the Serengeti and Masai Mara. Witness the Great Migration, spot the Big Five, and experience the raw beauty of the African wilderness with expert guides.',
    maxGuests: 10,
    category: 'wildlife',
    status: 'published',
    thumbnail: 'package-39c9e0fa-bc71-4988-874b-7336d1ba33ac-1755557403551.jpg',
    organizationDomain: 'umbrella.com',
    inclusions: [
      'Professional safari guide and driver',
      'Luxury tented camp accommodation',
      'All meals and beverages',
      'Game drives in 4x4 vehicles',
      'Park entrance fees',
      'Hot air balloon safari (Serengeti)',
      'Cultural visit to Masai village',
      'Airport transfers',
    ],
    exclusions: [
      'International flights to/from Africa',
      'Travel insurance and vaccinations',
      'Visa fees',
      'Personal expenses and tips',
      'Optional activities',
      'Alcoholic beverages (limited selection included)',
    ],
  },
  {
    name: 'European Grand Tour',
    destination: 'France, Italy, Spain',
    duration: '21 days',
    price: 3800.0,
    description:
      'Explore the best of Europe with this comprehensive tour covering France, Italy, and Spain. Visit iconic landmarks, taste world-class cuisine, and immerse yourself in the rich history and culture of these magnificent countries.',
    maxGuests: 20,
    category: 'cultural',
    status: 'published',
    thumbnail: 'package-62583975-b4ae-4664-969a-a42837ec108c-1755556832890.jpg',
    organizationDomain: 'acme.com',
    inclusions: [
      'Professional multilingual tour guide',
      '4-star hotel accommodation',
      'Daily breakfast and selected meals',
      'Private coach transportation',
      'Entrance fees to major attractions',
      'Wine tasting in Tuscany',
      'Flamenco show in Seville',
      'Eiffel Tower skip-the-line tickets',
    ],
    exclusions: [
      'International flights to/from Europe',
      'Travel insurance',
      'Personal expenses and shopping',
      'Additional meals not specified',
      'Optional excursions',
      'Alcoholic beverages (except wine tasting)',
    ],
  },
  {
    name: 'Budget Backpacking Southeast Asia',
    destination: 'Thailand, Vietnam, Cambodia',
    duration: '18 days',
    price: 1200.0,
    description:
      'Discover the vibrant cultures and stunning landscapes of Southeast Asia on this budget-friendly backpacking adventure. From bustling cities to pristine beaches, experience the best of Thailand, Vietnam, and Cambodia.',
    maxGuests: 16,
    category: 'budget',
    status: 'published',
    thumbnail: 'package-9490f9e0-2af5-41b9-b8a8-474f67968ae8-1755553728141.jpg',
    organizationDomain: 'globex.co',
    inclusions: [
      'Experienced local guides',
      'Hostel and guesthouse accommodation',
      'Daily breakfast',
      'Local transportation (buses, trains)',
      'Entrance fees to major sites',
      'Cooking class in Thailand',
      'Halong Bay cruise',
      'Angkor Wat temple tour',
    ],
    exclusions: [
      'International flights to/from Asia',
      'Travel insurance',
      'Most meals (except breakfast)',
      'Personal expenses and shopping',
      'Optional activities',
      'Alcoholic beverages',
    ],
  },
];
