export const users = [
  {
    name: 'Alice Johnson',
    email: 'alice@acme.com',
    phone: '+1-555-1234',
    password: 'hashed_password_1',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'Bob Smith',
    email: 'bob@globex.co',
    phone: '+1-555-5678',
    password: 'hashed_password_2',
    isActive: true,
    notificationsEnabled: false,
    newsletterSubscribed: true,
    organizationDomain: 'globex.co',
  },
  {
    name: 'Carol Williams',
    email: 'carol@initech.org',
    phone: '+1-555-9012',
    password: 'hashed_password_3',
    isActive: false,
    notificationsEnabled: false,
    newsletterSubscribed: false,
    organizationDomain: 'initech.org',
  },
  {
    name: 'David Brown',
    email: 'david@umbrella.com',
    phone: '+1-555-3456',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: true,
    organizationDomain: 'umbrella.com',
  },
  // Additional Users from Employee Seed
  {
    name: 'Sarah Wilson',
    email: 'sarah.wilson@acme.com',
    phone: '+1-555-1235',
    password: 'hashed_password_1',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'Michael Chen',
    email: 'michael.chen@acme.com',
    phone: '+1-555-1236',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@acme.com',
    phone: '+1-555-1237',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'James Thompson',
    email: 'james.thompson@globex.co',
    phone: '+1-555-5679',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },
  {
    name: 'Lisa Park',
    email: 'lisa.park@globex.co',
    phone: '+1-555-5680',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },
  {
    name: 'David Kumar',
    email: 'david.kumar@globex.co',
    phone: '+1-555-5681',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },
  {
    name: 'Jennifer Lee',
    email: 'jennifer.lee@initech.org',
    phone: '+1-555-9013',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'initech.org',
  },
  {
    name: 'Robert Martinez',
    email: 'robert.martinez@initech.org',
    phone: '+1-555-9014',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'initech.org',
  },
  {
    name: 'Dr. Amanda Foster',
    email: 'amanda.foster@umbrella.com',
    phone: '+1-555-3457',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },
  {
    name: 'Dr. Kevin Zhang',
    email: 'kevin.zhang@umbrella.com',
    phone: '+1-555-3458',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },
  {
    name: 'Dr. Maria Santos',
    email: 'maria.santos@umbrella.com',
    phone: '+1-555-3459',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },
  {
    name: 'Dr. Thomas Anderson',
    email: 'thomas.anderson@umbrella.com',
    phone: '+1-555-3460',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },

  // Finance Team Users
  {
    name: 'Mike Finance',
    email: 'mike.finance@acme.com',
    phone: '+1-555-0001',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'Kate Ledger',
    email: 'kate.ledger@initech.org',
    phone: '+1-555-0002',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'initech.org',
  },

  // Booking Team Users
  {
    name: 'Linda Reserve',
    email: 'linda.reserve@acme.com',
    phone: '+1-555-0003',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'John Booking',
    email: 'john.booking@globex.co',
    phone: '+1-555-0004',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },

  // Leads Team Users
  {
    name: 'Sara Sales',
    email: 'sara.sales@globex.co',
    phone: '+1-555-0005',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },
  {
    name: 'Becky Lead',
    email: 'becky.lead@umbrella.com',
    phone: '+1-555-0006',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },

  // Operations Team Users
  {
    name: 'Steve Ops',
    email: 'steve.ops@umbrella.com',
    phone: '+1-555-0007',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },
  {
    name: 'John Logistics',
    email: 'john.logistics@globex.co',
    phone: '+1-555-0008',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },

  // Acme Expansion Users
  {
    name: 'Alice Finance',
    email: 'alice.finance@acme.com',
    phone: '+1-555-0101',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'Bob Finance',
    email: 'bob.finance@acme.com',
    phone: '+1-555-0102',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'Carol Booking',
    email: 'carol.booking@acme.com',
    phone: '+1-555-0103',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'David Reserve',
    email: 'david.reserve@acme.com',
    phone: '+1-555-0104',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },

  // Globex Expansion Users
  {
    name: 'Eve Booking',
    email: 'eve.booking@globex.co',
    phone: '+1-555-0201',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },
  {
    name: 'Frank Sales',
    email: 'frank.sales@globex.co',
    phone: '+1-555-0202',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },
  {
    name: 'Grace Ops',
    email: 'grace.ops@globex.co',
    phone: '+1-555-0203',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'globex.co',
  },

  // Initech Expansion Users
  {
    name: 'Hank Finance',
    email: 'hank.finance@initech.org',
    phone: '+1-555-0301',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'initech.org',
  },
  {
    name: 'Ivy Ledger',
    email: 'ivy.ledger@initech.org',
    phone: '+1-555-0302',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'initech.org',
  },

  // Umbrella Expansion Users
  {
    name: 'Jack Leads',
    email: 'jack.leads@umbrella.com',
    phone: '+1-555-0401',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },
  {
    name: 'Karen Ops',
    email: 'karen.ops@umbrella.com',
    phone: '+1-555-0402',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },
  {
    name: 'Leo Logistics',
    email: 'leo.logistics@umbrella.com',
    phone: '+1-555-0403',
    password: 'password123',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'umbrella.com',
  },
];
