export const users = [
  {
    name: 'Alice Johnson',
    email: 'alice@acme.com',
    phone: '+1-555-1234',
    password: 'hashed_password_1',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: false,
    organizationDomain: 'acme.com',
  },
  {
    name: 'Bob Smith',
    email: 'bob@globex.com',
    phone: '+1-555-5678',
    password: 'hashed_password_2',
    isActive: true,
    notificationsEnabled: false,
    newsletterSubscribed: true,
    organizationDomain: 'globex.co',
  },
  {
    name: 'Carol Williams',
    email: 'carol@initech.com',
    phone: '+1-555-9012',
    password: 'hashed_password_3',
    isActive: false,
    notificationsEnabled: false,
    newsletterSubscribed: false,
    organizationDomain: 'initech.org',
  },
  {
    name: 'David Brown',
    email: 'david@umbrella.com',
    phone: '+1-555-3456',
    password: 'hashed_password_4',
    isActive: true,
    notificationsEnabled: true,
    newsletterSubscribed: true,
    organizationDomain: 'umbrella.com',
  },
];
